provider:
  version: 0.2

routes:
  democom:
    fqdn: demo.com
    routes:
      - name: api
        namespace: other
        prefix: /api/assets
        redirect: www.demo.com

functions:
  assets_1:
    name: assets
    version: 0.1
    annotations:
      example: eg
    build_args:
      LDFLAGS: "-w -s -extldflags '-static -pthread'"
    env:
      EXAMPLE: eg
    envs:
      - .env/common
    secrets:
      - .secrets/assets
    routes:
      - name: api
        fqdn: demo.com
        prefix: /api/assets

  assets_2:
    name: assets
    version: 0.2
    annotations:
      example: eg
    build_args:
      LDFLAGS: "-w -s -extldflags '-static -pthread'"
    env:
      EXAMPLE: eg
    envs:
      - .env/common
    secrets:
      - .secrets/assets
    routes:
      - name: api2
        fqdn: demo.com
        prefix: /api/assets

  profile:
    template: golang
    version: 0.1
    annotations:
      example: eg
    service_account: aab
    limits:
      cpu: "100m"
      memory: "100Mi"
    env:
      EXAMPLE: eg
    envs:
      - .env/common
    secrets:
      - .secrets/sops
    routes:
      - name: api2
        fqdn: demo.com
        prefix: /api/profile
        redirect: www.demo.com